/**
 * Consent & Disclaimer — Spec §6.1, UI Upgrade U3
 *
 * "Clinical Glass" restyle:
 * - Screen wrapper with gradient mesh + blob accents
 * - Terms sections in elevated GlassCard
 * - Clean themed checkbox with primary active state
 * - Preserved logic: scroll-gate & checkbox acceptance, API call, role routing, viewOnly mode
 */

import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
} from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '@/hooks/use-theme';
import { TypographyScale, Spacing, Radius } from '@/constants/theme';
import { Screen } from '@/components/ui/Screen';
import { GlassCard } from '@/components/ui/GlassCard';
import Button from '@/components/ui/Button';
import { acceptConsent } from '@/services/authApi';
import { useAuthStore } from '@/store/authStore';

export default function ConsentScreen() {
  const { colors } = useTheme();
  const { viewOnly } = useLocalSearchParams<{ viewOnly?: string }>();
  const isViewOnly = viewOnly === 'true';

  const [hasAcceptedTerms, setHasAcceptedTerms] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [apiError, setApiError] = useState('');

  const setUser = useAuthStore((s) => s.setUser);

  async function handleAccept() {
    setApiError('');
    setIsLoading(true);

    try {
      const updatedUser = await acceptConsent();
      setUser(updatedUser);

      // Route by role
      if (updatedUser.role === 'reviewer') {
        router.replace('/(reviewer)/dashboard');
      } else {
        router.replace('/(staff)/home');
      }
    } catch (error: any) {
      if (error?.message?.includes('Network')) {
        setApiError('Unable to connect to the server. Check your internet connection.');
      } else {
        setApiError(
          error?.response?.data?.detail || 'Failed to record consent. Please try again.',
        );
      }
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <Screen safeArea={false}>
      <View style={styles.container}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={[TypographyScale.h1, styles.title, { color: colors.textPrimary }]}>
            Consent & Disclaimer
          </Text>
          <Text style={[TypographyScale.body, styles.subtitle, { color: colors.textSecondary }]}>
            Please review the following clinical terms before proceeding.
          </Text>
        </View>

        {/* Scrollable Terms Content */}
        <ScrollView
          style={styles.scroll}
          contentContainerStyle={styles.scrollContent}
          showsVerticalScrollIndicator={true}
        >
          <GlassCard tint="elevated" elevation="raised" radius="lg" style={styles.sectionCard}>
            <View style={styles.cardPadding}>
              <Text style={[TypographyScale.h3, styles.sectionTitle, { color: colors.textPrimary }]}>
                Data Collection
              </Text>
              <Text style={[TypographyScale.body, styles.bodyText, { color: colors.textSecondary }]}>
                This system collects clinical data including symptom descriptions, medical images
                (photographs), and vital signs measurements. This data is used exclusively
                for AI-assisted risk screening within your healthcare facility.
              </Text>
            </View>
          </GlassCard>

          <GlassCard tint="elevated" elevation="raised" radius="lg" style={styles.sectionCard}>
            <View style={styles.cardPadding}>
              <Text style={[TypographyScale.h3, styles.sectionTitle, { color: colors.textPrimary }]}>
                AI-Assisted Screening
              </Text>
              <Text style={[TypographyScale.body, styles.bodyText, { color: colors.textSecondary }]}>
                The Clinical Risk Stratification System uses artificial intelligence to provide
                risk assessments. These assessments are decision-support tools only and are
                NOT a medical diagnosis. All results must be reviewed and validated by a
                qualified healthcare professional.
              </Text>
            </View>
          </GlassCard>

          <GlassCard tint="elevated" elevation="raised" radius="lg" style={styles.sectionCard}>
            <View style={styles.cardPadding}>
              <Text style={[TypographyScale.h3, styles.sectionTitle, { color: colors.textPrimary }]}>
                Clinical Disclaimer
              </Text>
              <Text style={[TypographyScale.body, styles.bodyText, { color: colors.textSecondary }]}>
                This tool is not a substitute for professional medical judgment. Risk levels
                (Low, Medium, High) are probability estimates generated by machine learning
                models and should be used as one input among many in clinical decision-making.
                Always follow established clinical protocols and exercise professional judgment.
              </Text>
            </View>
          </GlassCard>

          <GlassCard tint="elevated" elevation="raised" radius="lg" style={styles.sectionCard}>
            <View style={styles.cardPadding}>
              <Text style={[TypographyScale.h3, styles.sectionTitle, { color: colors.textPrimary }]}>
                Data Storage
              </Text>
              <Text style={[TypographyScale.body, styles.bodyText, { color: colors.textSecondary }]}>
                Patient data and assessment results are stored securely in a MongoDB database.
                Data is associated with your healthcare facility and is accessible only to
                authorized staff and reviewers within your organization.
              </Text>
            </View>
          </GlassCard>

          <GlassCard tint="elevated" elevation="raised" radius="lg" style={styles.sectionCard}>
            <View style={styles.cardPadding}>
              <Text style={[TypographyScale.h3, styles.sectionTitle, { color: colors.textPrimary }]}>
                Your Responsibilities
              </Text>
              <Text style={[TypographyScale.body, styles.bodyText, { color: colors.textSecondary }]}>
                By using this system, you acknowledge that:{'\n\n'}
                • You are a qualified healthcare professional or authorized reviewer.{'\n'}
                • You will use AI risk assessments as one input among many, never as a sole basis for clinical decisions.{'\n'}
                • You will follow all applicable clinical protocols and regulatory requirements.{'\n'}
                • You will protect patient data and use it only for authorized clinical purposes.
              </Text>
            </View>
          </GlassCard>
        </ScrollView>

        {/* Footer with Checkbox & Action */}
        <View
          style={[
            styles.footer,
            {
              borderTopColor: colors.glassBorder,
              backgroundColor: colors.surface,
            },
          ]}
        >
          {apiError ? (
            <View
              style={[
                styles.errorBanner,
                {
                  backgroundColor: `${colors.danger}15`,
                  borderColor: `${colors.danger}35`,
                },
              ]}
            >
              <Text style={[TypographyScale.caption, { color: colors.danger, fontWeight: '600' }]}>
                {apiError}
              </Text>
            </View>
          ) : null}

          {isViewOnly ? (
            <Button
              title="Go Back"
              onPress={() => router.back()}
              variant="outline"
            />
          ) : (
            <>
              <TouchableOpacity
                style={styles.checkboxContainer}
                onPress={() => setHasAcceptedTerms(!hasAcceptedTerms)}
                activeOpacity={0.7}
              >
                <View
                  style={[
                    styles.checkbox,
                    {
                      borderColor: hasAcceptedTerms ? colors.primary : colors.borderStrong,
                      backgroundColor: hasAcceptedTerms ? colors.primary : colors.surfaceSunken,
                    },
                  ]}
                >
                  {hasAcceptedTerms && (
                    <Ionicons name="checkmark" size={16} color={colors.textOnPrimary} />
                  )}
                </View>
                <Text style={[TypographyScale.bodySm, styles.checkboxLabel, { color: colors.textPrimary }]}>
                  I have read and agree to the clinical disclaimer and data policies above.
                </Text>
              </TouchableOpacity>

              <Button
                title="I Understand and Consent"
                onPress={handleAccept}
                disabled={!hasAcceptedTerms || isLoading}
                loading={isLoading}
              />
            </>
          )}
        </View>
      </View>
    </Screen>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.xxl,
    paddingBottom: Spacing.md,
  },
  title: {
    marginBottom: Spacing.xxs,
  },
  subtitle: {
    lineHeight: 20,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.md,
    gap: Spacing.sm,
  },
  sectionCard: {
    marginBottom: Spacing.xxs,
  },
  cardPadding: {
    padding: Spacing.md,
  },
  sectionTitle: {
    marginBottom: Spacing.xs,
  },
  bodyText: {
    lineHeight: 21,
  },
  footer: {
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    borderTopWidth: 1,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Spacing.md,
    minHeight: 44,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: Radius.sm,
    borderWidth: 2,
    marginRight: Spacing.sm,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxLabel: {
    flex: 1,
    lineHeight: 18,
  },
  errorBanner: {
    borderWidth: 1,
    borderRadius: Radius.md,
    padding: Spacing.sm,
    marginBottom: Spacing.sm,
  },
});
