/**
 * Consent & Disclaimer — Spec §6.1
 *
 * Required first-use screen per Scope §4/§5.1.
 * Displays: what data is collected, how it's used, clinical disclaimer,
 * data storage notice.
 *
 * "A single 'I Understand and Consent' button, disabled until the user
 *  scrolls to the bottom (onScrollEndDrag check) — this isn't decorative,
 *  it's a genuine consent-capture pattern for a healthcare tool."
 *
 * Calls POST /auth/consent. Cannot be skipped or dismissed without accepting.
 */

import React, { useState, useRef } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  type NativeSyntheticEvent,
  type NativeScrollEvent,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { Colors, Typography, Spacing } from '@/constants/theme';
import Button from '@/components/ui/Button';
import { acceptConsent } from '@/services/authApi';
import { useAuthStore } from '@/store/authStore';

export default function ConsentScreen() {
  const [hasScrolledToBottom, setHasScrolledToBottom] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [apiError, setApiError] = useState('');

  const setUser = useAuthStore((s) => s.setUser);
  const user = useAuthStore((s) => s.user);

  /**
   * Scroll-to-bottom detection.
   * Checks if contentOffset.y + layoutHeight >= contentSize.height (within a small threshold).
   * This is the genuine consent-capture pattern per Spec §6.1.
   */
  function handleScroll(event: NativeSyntheticEvent<NativeScrollEvent>) {
    if (hasScrolledToBottom) return; // Already enabled, no need to recompute

    const { contentOffset, layoutMeasurement, contentSize } = event.nativeEvent;
    const distanceFromBottom = contentSize.height - (contentOffset.y + layoutMeasurement.height);

    // Enable when within 20px of the bottom
    if (distanceFromBottom <= 20) {
      setHasScrolledToBottom(true);
    }
  }

  async function handleAccept() {
    setApiError('');
    setIsLoading(true);

    try {
      const updatedUser = await acceptConsent();
      setUser(updatedUser);

      // Route by role
      if (updatedUser.role === 'reviewer') {
        router.replace('/(reviewer)/dashboard');
      } else {
        router.replace('/(staff)/home');
      }
    } catch (error: any) {
      if (error?.message?.includes('Network')) {
        setApiError('Unable to connect to the server. Check your internet connection.');
      } else {
        setApiError(
          error?.response?.data?.detail || 'Failed to record consent. Please try again.',
        );
      }
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <SafeAreaView style={styles.safe}>
      <View style={styles.header}>
        <Text style={styles.title}>Consent & Disclaimer</Text>
        <Text style={styles.subtitle}>
          Please review the following before proceeding.
        </Text>
      </View>

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.scrollContent}
        onScroll={handleScroll}
        scrollEventThrottle={100}
        showsVerticalScrollIndicator={true}
      >
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Data Collection</Text>
          <Text style={styles.body}>
            This system collects clinical data including symptom descriptions, medical images
            (photographs), and vital signs measurements. This data is used exclusively
            for AI-assisted risk screening within your healthcare facility.
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>AI-Assisted Screening</Text>
          <Text style={styles.body}>
            The Clinical Risk Stratification System uses artificial intelligence to provide
            risk assessments. These assessments are decision-support tools only and are
            NOT a medical diagnosis. All results must be reviewed and validated by a
            qualified healthcare professional.
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Clinical Disclaimer</Text>
          <Text style={styles.body}>
            This tool is not a substitute for professional medical judgment. Risk levels
            (Low, Medium, High) are probability estimates generated by machine learning
            models and should be used as one input among many in clinical decision-making.
            Always follow established clinical protocols and exercise professional judgment.
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Data Storage</Text>
          <Text style={styles.body}>
            Patient data and assessment results are stored securely in a MongoDB database.
            Data is associated with your healthcare facility and is accessible only to
            authorized staff and reviewers within your organization.
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Your Responsibilities</Text>
          <Text style={styles.body}>
            By using this system, you acknowledge that:{'\n\n'}
            • You are a qualified healthcare professional or authorized reviewer.{'\n'}
            • You will use AI risk assessments as one input among many, never as a sole basis for clinical decisions.{'\n'}
            • You will follow all applicable clinical protocols and regulatory requirements.{'\n'}
            • You will protect patient data and use it only for authorized clinical purposes.
          </Text>
        </View>

        {/* Extra space at bottom to ensure user must actually scroll */}
        <View style={styles.scrollBottomPad} />
      </ScrollView>

      <View style={styles.footer}>
        {apiError ? (
          <View style={styles.errorBanner}>
            <Text style={styles.errorBannerText}>{apiError}</Text>
          </View>
        ) : null}

        <Button
          title="I Understand and Consent"
          onPress={handleAccept}
          disabled={!hasScrolledToBottom || isLoading}
          loading={isLoading}
        />

        {!hasScrolledToBottom && (
          <Text style={styles.footerNote}>
            ↓  Scroll to bottom to enable
          </Text>
        )}
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  header: {
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.lg,
    paddingBottom: Spacing.md,
  },
  title: {
    fontFamily: Typography.bold,
    fontSize: 24,
    color: Colors.textPrimary,
  },
  subtitle: {
    fontFamily: Typography.regular,
    fontSize: 14,
    color: Colors.textSecondary,
    marginTop: Spacing.xxs,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.lg,
  },
  section: {
    backgroundColor: Colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
  },
  sectionTitle: {
    fontFamily: Typography.semiBold,
    fontSize: 16,
    color: Colors.textPrimary,
    marginBottom: Spacing.xs,
  },
  body: {
    fontFamily: Typography.regular,
    fontSize: 14,
    color: Colors.textSecondary,
    lineHeight: 21,
  },
  scrollBottomPad: {
    height: 24,
  },
  footer: {
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    backgroundColor: Colors.surface,
  },
  footerNote: {
    fontFamily: Typography.regular,
    fontSize: 12,
    color: Colors.textSecondary,
    textAlign: 'center',
    marginTop: Spacing.xs,
  },
  errorBanner: {
    backgroundColor: Colors.riskHigh + '12',
    borderWidth: 1,
    borderColor: Colors.riskHigh + '30',
    borderRadius: 10,
    padding: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  errorBannerText: {
    fontFamily: Typography.medium,
    fontSize: 13,
    color: Colors.riskHigh,
    lineHeight: 19,
  },
});
